Improved venv function

diff --git a/functions/venv b/functions/venv
--- a/functions/venv
+++ b/functions/venv
@@ -1,45 +1,45 @@
-# Activate a venv if we have one
+print()  { echo "$@" >&2 }
+yield()  { echo "$@"     }
 
-subdirs() {
-    find . -mindepth 1 -maxdepth 1 -type d
-}
-
-search_for_venv() {
+activate_dirs() {
     local dir
-    for dir in `subdirs`; do
+    for dir in $(find . -mindepth 1 -maxdepth 1 -type d); do
         if [ -f "$dir/bin/activate" ]; then
-            echo "$dir"        
+            yield $dir
         fi
     done
 }
 
-# Locate venv
-if [ "$#" -eq 1 ]; then
-    venv_dir=$1
-elif [ "$#" -eq 0 ]; then
-    candidates=$(search_for_venv)
-    if [ -z "$candidates" ]; then
-        echo "No virtual environment found."
+select_venv() {
+    local candidates=("$@")
+
+    if [ ${#candidates[@]} -eq 0 ]; then
+        print "No virtual environments found." 
         return 1
-    elif [ `echo "$candidates" | wc -l` -gt 1 ]; then
-        echo "Multiple virtual environments found."
-        echo "Candidates: $candidates"
-        return 1
+    elif [ ${#candidates[@]} -eq 1 ]; then
+        yield "${candidates[1]}"
     else
-        venv_dir=$(echo "$candidates" | head -n 1)
+        print "Multiple virtual environments found." 
+        print "Please select one:" 
+        select venv_dir in "${candidates[@]}"; do
+            [ -n "$venv_dir" ] && echo "$venv_dir" && return
+        done
     fi
-else
-    echo "Usage: venv [<path_to_virtualenv>]"
-    return 1
-fi
+}
 
+activate_venv() {
+    local venv_dir="$1"
+    local venv_activate="$venv_dir/bin/activate"
 
-venv_activate="$venv_dir/bin/activate"
-if [ -f "$venv_activate" ]; then
-    source "$venv_activate" && \
-        echo "Activated virtual environment: $venv_dir" || \
-        echo "Failed to activate virtual environment: $venv_dir"
-else
-    echo "Virtual environment not found at: $venv_dir"
-    return 1
-fi
+    if [ -f "$venv_activate" ]; then
+        source "$venv_activate" && \
+            echo "Activated virtual environment: $venv_dir" || \
+            echo "Failed to activate virtual environment: $venv_dir" >&2
+    else
+        echo "Error: Virtual environment activation script not found in $venv_dir" >&2
+        return 1
+    fi
+}
+
+venv_dir=$(select_venv $(activate_dirs)) || exit 1
+activate_venv "$venv_dir"
